name: Docker Image CI for GHCR

on:
  push:

env:
  IMAGE_NAME: bcit-ltc/${{ github.ref_name }}

jobs:

  build-and-push-app-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:

      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/setup-buildx-action@v3

      - name: Generate container metadata
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        env:
          DOCKER_METADATA_ANNOTATIONS_LEVELS: manifest,index
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: type=sha,format=long
          flavor: |
            latest=true

      - uses: docker/build-push-action@v6
        env:
          DOCKER_BUILD_RECORD_UPLOAD: false
          DOCKER_BUILD_SUMMARY: false
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          annotations: ${{ steps.meta.outputs.annotations }}
          provenance: true    # or could use `attest-build-provenance`` step below
          sbom: false
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Sign images to ensure authenticity
      - uses: sigstore/cosign-installer@v3

      - name: Cosign sign (keyless, by digest)
        env:
          DIGEST: ${{ steps.build.outputs.digest }}
        run: cosign sign --yes "${IMAGE_NAME}@${DIGEST}"
